version: '3.8'

services:
  app:
    build: .
    container_name: go_crud_app
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db_crud_echo
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: go_crud_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_crud_echo
    ports:
      - "3307:3306" # Expose on 3307 to avoid conflict with local MySQL
    volumes:
      - db_data:/var/lib/mysql
      - ./database/migration.sql:/docker-entrypoint-initdb.d/init.sql # Auto-run migration
    restart: always

volumes:
  db_data:
